---
development:
  cloud_name: mg08
  api_key: '718975778686759'
  api_secret: SqNBBv4_Ni2zNjjoUAiSkfq-6mc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: mg08
  api_key: '718975778686759'
  api_secret: SqNBBv4_Ni2zNjjoUAiSkfq-6mc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: mg08
  api_key: '718975778686759'
  api_secret: SqNBBv4_Ni2zNjjoUAiSkfq-6mc
  enhance_image_tag: true
  static_image_support: false
