# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba62152b8291c3fe4d860428654b130f0900d72003219e09ca4d2214cf416a8d7e952bc57c1ab1ec10804124f7fd8df6c8fbbaaa2b0df968085c075c80078b4

test:
  secret_key_base: 6cda399609f2809a89628b8dda3d1643937c58d55f88da179b3871f19e5a7a357d54ab9e93b7b182ea7b371a0c44b5eabccd112a61464ff68d94c2f8b643dc69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
